version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: onlysales
      POSTGRES_PASSWORD: onlysales123
      POSTGRES_DB: onlysalesdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://onlysales:onlysales123@db:5432/onlysalesdb
    depends_on:
      - db
volumes:
  pgdata: 